# Generated by Django 5.2 on 2026-08-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newsletterform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterForm',
            new_name='Newsletter',
        ),
    ]
